name: node_crud
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  add_to_cart_animation: ^2.0.3
  animate_do: ^3.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  palette_generator: ^0.3.3+2
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  string_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/shoes/
    - assets/shoes/cat1/
    - assets/shoes/cat2/
    - assets/shoes/cat3/
